### ISSUE TITLE
文件系统能否引入icloud drive来存储多个插件之间的共用数据

### ISSUE THREAD

**Issue by miniers** [cyanzhong/xTeko#16]
😂或者整个插件的文件系统都放在icloud drive，这样写插件改插件就更简单，不用直接在手机改了
workflow现在就支持向icloud drive存储数据

**Comment by cyanzhong** [comment]
可以引入一个公共区域，iCloud Drive 之后再考虑

**Comment by cyanzhong** [comment]
从 v3.1.2 Build 63 开始，目录以 `shared://` 开头即为在共享区域读写。

iCloud Drive 也将会实现，不过不是最近的几个版本。

**Comment by miniers** [comment]
👍🏿棒棒哒，期待icloud drive

**Comment by cyanzhong** [comment]
v3.2.1 已经支持 `$drive` 接口：https://docs.xteko.com/#/file/drive

**Comment by miniers** [comment]
😍赞赞赞

**Comment by miniers** [comment]
使用时发现一个疑问，Pin在icloud drive中生成的文件夹，只能在ios上查看，网页版和mac下的icloud drive都看不到Pin的文件夹，我生成文件后大概等了一个小时，通过ios文件中查看到该文件的状态为已上传，还是无法再网页版和mac中查看到
workflow 生成的文件是可以查看到的
