### ISSUE TITLE
反馈调试效时率问题

### ISSUE THREAD

**Issue by xperezxin** [cyanzhong/xTeko#29]
①在调试代码时，如果脚本出现错误，就会出现一个错误的bug虫标志，当修改代码之后，那bug虫依然还在，必须保存之后退出再进入才可以。这样太耽误时间了。
1.是不是可以加入多个按钮调试(比如"运行按钮"，"bug按钮")
2.或者出现错误之后修改完，立刻出现运行按钮来测试
②在商店里面不能进入代码，只有官网，也要返回到xteko区。

反馈来之制作者长期制作时出现阻挡制作效率的痛苦

**Comment by microxiao** [comment]
商店里面是否可以有 立即下载安装进入脚本编辑区和只安装

**Comment by cyanzhong** [comment]
其实是在编辑器运行无论如何都会出现虫子

**Comment by microxiao** [comment]
所以调试的时候，运行一遍出现虫子后，只能返回再进入这个脚本了，才能运行😔

**Comment by microxiao** [comment]
发现了：
原来虫子把执行按钮挡住了，拖开就可以。
