### ISSUE TITLE
$http.post()方法怎样传递body参数? 响应回调怎么获取response headers ?

### ISSUE THREAD

**Issue by wxlzmt** [cyanzhong/xTeko#3]
form-data类型的参数怎么传?
x-www-form-urlencoded类型的参数怎么传?
用这种方式貌似不好使
```
$http.post({
    url: "xxx",
    body: {
        cont: "abc",
        ppp: "123"
    },
    header: {
        'Content-Type': 'application/x-www-form-urlencoded'
    },
    handler: function(resp) {
        //略
    }
});
```

另外,响应回调怎么获取response headers ?

**Comment by BeBeBerr** [comment]
同问post参数怎么传

**Comment by cyanzhong** [comment]
抱歉 body 参数有个 bug，现在已修复在最新的 TestFlight 版本上。

发邮件到 log.e@qq.com 申请 TF，或者等待即将上线的 3.0.1 版本。

文档已更新：https://docs.xteko.com/#/foundation/network

**Comment by cyanzhong** [comment]
文件上传可以使用 `$http.upload` 接口

**Comment by cyanzhong** [comment]
完整的 form-data 支持将会在今晚的 TF

**Comment by BeBeBerr** [comment]
今天试了下post 没有问题了。修复的很快，赞一个👍🏻

**Comment by cyanzhong** [comment]
已更新，在 v3.0.1 Build 33 里面：

- $http 支持了 form-data，请查看最新文档
- 调整了 $http 部分参数名，请查看最新文档

**Comment by cyanzhong** [comment]
从 v3.0.2 Build 36 开始，`application/x-www-form-urlencoded` 需要手动指定，默认状况下是 application/json
