### ISSUE TITLE
关于延迟执行的疑问

### ISSUE THREAD

**Issue by dishuostec** [cyanzhong/xTeko#30]
请问如何实现取消单次延迟执行的定时器？类似的 js 代码：
```javascript
const foo = setTimeout(()=>{}, 1000);
clearTimeout(foo);
```

文档 https://docs.xteko.com/#/foundation/thread 写了4种延迟执行的方法

$thread.background(object)
$thread.main(object)
$delay(number, function)
$timer.schedule(object)

只有 $timer.schedule() 可以被取消，没有取消一次性延迟任务的方法。

**Comment by cyanzhong** [comment]
目前没有这样的 pattern

你可以自己实现类似的逻辑。
