### ISSUE TITLE
固定脚本导致tab无法切换

### ISSUE THREAD

**Issue by qupei2u** [cyanzhong/xTeko#33]
将demo的汇率转换设置为固定的脚本，然后切换到这个tab上点击输入框。然后系统弹出的数字键盘就无法关闭了，只能退出APP重新打开。
机型：iPhoneSE，10.3.3

![](http://7xobbh.com1.z0.glb.clouddn.com/17-12-20/62566412.jpg)

**Comment by cyanzhong** [comment]
这个问题有两个层面：

1. 我们永远无法阻止一个脚本做成这个样子
2. 我们可以让默认的脚本不出现这个情况

解决方案是：

1. 我会在之后的默认脚本里面增加点击空白处收起键盘的功能
2. 自己设置的脚本也要尽量避免出现这种情况
3. 我会在这个界面增加一个设置按钮

**Comment by AllenGuan** [comment]
收起鍵盤的功能要怎麼寫？

**Comment by cyanzhong** [comment]
```js
tapped: function() {
  $("id-of-the-input-view").blur()
}
```
