### ISSUE TITLE
如何将剪贴板的带格式文字变成纯文本？

### ISSUE THREAD

**Issue by galaxy001** [cyanzhong/xTeko#39]
希望能帮忙写个可以在Pin下用的jsbox的例子，用来将剪贴板的带格式文字，粘贴为纯文本（plain text）。

**Comment by cyanzhong** [comment]
$clipboard.text 取出来的就是纯文本

**Comment by galaxy001** [comment]
在JS扩展下，新建
```
function run() {
    return "|text|";
}
```
可以实现去掉格式。

如何加入将`"|text|"`粘贴到当前光标活动的地方的功能？
