### ISSUE TITLE
$photo.pick() 选取 gif 的时候，返回数据不是 data ？

### ISSUE THREAD

**Issue by wr1241** [cyanzhong/xTeko#41]
Hi，这个对象好像是 PLXPCShMemData，请问我怎样能获取 gif 的二进制数据？

**Comment by cyanzhong** [comment]
format: data 的时候是 data

**Comment by wr1241** [comment]
嗯，我使用了`format: "data"`这个参数，不过 `resp.data.string`是 undefined，是不是因为我选择的 gif 图文件尺寸比较大？有 2M+

**Comment by wr1241** [comment]
我想做的是把 gif 帧序列反转，就是反着播放 gif 图。网上有好多好好笑的反转gif，但是我脑补不回去正着放是什么画面。。。

大概思路是 decode -> encode 存成新文件。

**Comment by wr1241** [comment]
我找到一个解决方案(ง •̀_•́)ง
