### ISSUE TITLE
有关 $env 的一些疑问

### ISSUE THREAD

**Issue by Vizards** [cyanzhong/xTeko#5]
此疑问来自 xTeko 插件商店的插件 `xTeko 收藏夹` 和 https://github.com/cyanzhong/xTeko/pull/4

根据 xTeko 文档 [应用 - xTeko](https://docs.xteko.com/#/foundation/app?id=appenv)，判断扩展是否运行在通知中心的方法是：

```js
if ($app.env == $env.today) {

}
```

但在运行时会报错 `ReferenceError: Can't find variable: $env`

根据 [常量 - xTeko](https://docs.xteko.com/#/data/constant) 中的方法指定 `$env` 后可以正常运行：

```diff
+ var $env = {
+     app: 1 << 0,
+     today: 1 << 1,
+     ...
+ }
  if ($app.env == $env.today) {

  }
```

条件所限，目前仅测试过在 iPhone 6s 的 10.3.3, 10.3.2, 10.0.2 上 100% 复现此问题，不知是否为个例？

**Comment by cyanzhong** [comment]
抱歉，这个需要最新的 TF 版本才行，或者是下一个上线的 App Store 版本
