### ISSUE TITLE
Does not seem to support Chinese encoding in http requests

### ISSUE THREAD

**Issue by BAZINGAyi** [cyanzhong/xTeko#53]
I use the VScode or read the phone Input Chinese character as parameters cannot be identified.

**Comment by cyanzhong** [comment]
Can you provide a test case if possible?

**Comment by BAZINGAyi** [comment]
Sure, Thank you. 
Here is my request URL `https://free-api.heweather.com/s6/weather/lifestyle?key=***&&location=beijing` .

If I change the value of location from English to Chinese. 
eg: `https://free-api.heweather.com/s6/weather/lifestyle?key=***&&location=北京`

This request will be wrong but English will not happen.

**Comment by cyanzhong** [comment]
`URL Encode` is always needed for non-ascii characters.

**Comment by cyanzhong** [comment]
`encodeURI` is what you need.

**Comment by BAZINGAyi** [comment]
Thank you very much, the problem was solved.

Best wishes！
