### ISSUE TITLE
是否可以支持引入第三方扩展库？例如lodash等

### ISSUE THREAD

**Issue by miniers** [cyanzhong/xTeko#6]
自己写的扩展需要处理一些数据，如果能够引入lodash等扩展库的话将会方便很多

**Comment by cyanzhong** [comment]
理论上只要是非 browser-based 的库都可以引入，也做了相关的准备。

现实中还没有实现出来。

**Comment by miniers** [comment]
期待，
还有mac上开发时，现在是写了个node监控js文件变更post到内置的http服务来上传，
是否可以支持webdav或者ftp之类的，这样会更方便点😅

**Comment by cyanzhong** [comment]
如何在桌面端开发更为方便是一定会考虑的 🤔

**Comment by miniers** [comment]
![img_0248](https://user-images.githubusercontent.com/2039910/30052483-2c7577d6-9258-11e7-9200-9c193da1c851.jpg)
顺便提交一个bug，使用了一个list来内嵌TEXT组件用以输入内容，当text过多，编辑最后一个text的内容时，键盘会把text组件遮挡，包括原生键盘

**Comment by miniers** [comment]
`
$ui.render({
  layout: $layout.fill,
  views: [{
    type: "button",
    props: {
      title: "生成配置"
    },
    layout: function (make) {
      make.left.right.bottom.inset(10)
      make.height.equalTo(32)
    },
    events: {
      tapped: function (sender) {
        //selectItem()
      }
    }
  }, {
    type: "list",
    layout: function (make) {
      make.left.top.right.equalTo(0)
      make.bottom.equalTo($("button").top).offset(0)
    },
    props: {
      rowHeight: 150,
      data: ['1','2','3','4','5','6','7','8','9','10'].map(function (cus) {
        let cfg = cus;
        if(typeof cus === 'string'){
          cfg = {
            name:cus
          }
        }
        return {
          title: `${cfg.name} ${cfg.text?`(${cfg.text})`:''}`,
          rows: [{
            type: "text",
            props: {
              id: cfg.name,
              text:  '',
            },
            layout: function (make) {
              make.edges.inset(5);
            }
          }]
        }
      })
    }
  }]

})
`
这是例子

**Comment by miniers** [comment]
😂另外希望文件系统可以增加 icloud drive支持，现在保存的配置无法方便导入导出也是不爽呀🤓

**Comment by cyanzhong** [comment]
键盘遮挡问题你单开一条 issue 吧
