### ISSUE TITLE
JSBox 能够完成应用软件的自动化模拟操作吗？

### ISSUE THREAD

**Issue by L018** [cyanzhong/xTeko#61]
我看了开发文档，没有找到进行模拟操作的api，比如说某应用控件的点击输入等。
只找到了一个$app.openURL("weixin://")的接口，我没有太理解这个URL的作用，这个URL是和控件关联的吗？
我想知道能不能写出完成自动进行回复消息等之类的脚本。谢谢。

**Comment by cyanzhong** [comment]
Doing that on non-jailbroken devices is impossible.
