### ISSUE TITLE
当数组中有二进制数据 数组的API全部都有问题

### ISSUE THREAD

**Issue by CoderTonyChan** [cyanzhong/xTeko#64]
数组的API全部都有问题 
比如 
1.打印是空白
2.for循环 拿到数据全部是最后一个

**Comment by CoderTonyChan** [comment]
另外想问一下 
image 控件中 有一些图片要求 Referer 才能访问 有什么解决方法吗?

**Comment by cyanzhong** [comment]
请提供测试用的代码

**Comment by CoderTonyChan** [comment]
> 请提供测试用的代码

https://github.com/CoderTonyChan/JSBox-Repo/blob/03778d398cbf48ddc56c2431616c27656f5bf68b/HList%2B.js#L758

**Comment by Eric0625** [comment]
> > 请提供测试用的代码
> 
> https://github.com/CoderTonyChan/JSBox-Repo/blob/03778d398cbf48ddc56c2431616c27656f5bf68b/HList%2B.js#L758

老哥太稳了😂
