### ISSUE TITLE
code-server support

### ISSUE THREAD

**Issue by syslot** [cyanzhong/xTeko#70]
Hi,

JSBox 能否考虑特殊支持[code-server](https://github.com/cdr/code-server)?我尝试在iPadOS 上运行代码, code-server是个不错的选择. 然而 iOS/iPadOS Safari 不支持自定义快捷键. 看到JSBox可以自定义快捷键, 这个两个项目的组合可能会产生一个非常亮眼的刚需应用. 请作者考虑.

**Comment by cyanzhong** [comment]
Nice point, I will think about it.
