### ISSUE TITLE
Question: type definition for JSBox?

### ISSUE THREAD

**Issue by Soontao** [cyanzhong/xTeko#72]
Hello Developer, 

I find a simple type definition for JSBox at [here](https://github.com/xioxin/jsbox-ts-webpack/blob/master/src/global.d.ts), but its out of date. 
Does the product (JSBox) have a plan to publish the official type definition file ?

Thanks

**Comment by cyanzhong** [comment]
That's what I've been thinking, but honestly, I don't have a clear plan yet.

**Comment by Soontao** [comment]
Got it, closed. :)
