### ISSUE TITLE
想通过Runtime-C的方式，调用CoreMIDI的函数，应该如何写呢？

### ISSUE THREAD

**Issue by flashtd1** [cyanzhong/xTeko#82]
如题
我看给定的例子里都是class，可以进行实例化
但是CoreMIDI下的都是func，我使用$objc('xxxx')()会提示xxxx不是一个function
还有这方面有其他的参考文档吗，查起来有点没有头绪，感谢！

**Comment by cyanzhong** [comment]
JSBox 仅支持有限地调用 C 函数，https://docs.xteko.com/#/runtime/c?id=defc

对于参数类型复杂的函数则无法支持，此类需求建议还是自己写一个 App。
